FROM rust:latest AS builder
RUN apt-get update
RUN apt-get install musl-tools -y
RUN rustup target add x86_64-unknown-linux-musl
ADD lib/ lib/
ADD server/ server/
ADD server-logic/ server-logic/
RUN cd server && RUSTFLAGS=-Clinker=musl-gcc cargo build --release --bin pinochle-server --target=x86_64-unknown-linux-musl


FROM alpine:latest
COPY --from=builder /server/target/x86_64-unknown-linux-musl/release/pinochle-server /pinochle-server
CMD ["/pinochle-server"]