[package]
name = "pinochle-server"
version = "0.1.0"
authors = ["Sheyne Anderson <sheyne@sheyne.com>"]
edition = "2018"

[dependencies]
server-logic = { path = "../server-logic" }
warp = "0.2"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }