[package]
name = "pinochle-server"
version = "0.1.0"
authors = ["Sheyne Anderson <sheyne@sheyne.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"
pinochle-lib = { path = "../lib" }
serde = "1.0"
serde_json = "1.0"
strum = "0.1"
tungstenite = "0.10"
weak-table = "0.2"